yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"


urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_posts"),
    path("create/", views.new_post, name="new_post"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path("posts/<int:post_id>/comment", views.add_comment, name="add_comment"),
    path("follow/", views.follow_index, name="follow_index"),
    path(
        "profile/<str:username>/follow/",
        views.profile_follow,
        name="profile_follow",
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls import handler403, handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = "core.views.page_not_found"  # noqa
handler403 = "core.views.csrf_token"  # noqa
handler500 = "core.views.server_error"  # noqa

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls", namespace="posts")),
    path("auth/", include("users.urls", namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path("about/", include("about.urls", namespace="about")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATICFILES_DIRS
    )
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField("Текст поста", help_text="Введите текст поста")
    pub_date = models.DateTimeField("Дата публикации", auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="Автор",
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name="posts",
        blank=True,
        null=True,
        verbose_name="Группа",
        help_text="Выберите группу",
    )
    image = models.ImageField(
        "Картинка", upload_to="posts/", blank=True, null=True
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = [
            "-pub_date",
        ]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Пост",
        help_text="Пост комента",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Автор",
        help_text="Автор коммента",
    )
    text = models.TextField(
        verbose_name="Текст комментария", help_text="Текст нового комментария"
    )
    pub_date = models.DateTimeField(
        verbose_name="Дата публикации", auto_now_add=True
    )

    class Meta:
        ordering = [
            "-pub_date",
        ]

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower",
        verbose_name="Пользователь",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following",
        verbose_name="Автор",
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['author', 'user'],
                name='unique_follower'
            )
        ]

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ["text", "group", "image"]


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            "text",
        ]

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page
from django.views.decorators.http import require_http_methods

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User


@cache_page(20)
@require_http_methods(["GET"])
def index(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(
        request, "posts/index.html", {"page_obj": page_obj, "posts": posts}
    )


@require_http_methods(["GET"])
def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(
        request,
        "posts/group_list.html",
        {"group": group, "posts": posts, "page_obj": page_obj},
    )


@require_http_methods(["GET"])
def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    if request.user.is_authenticated:
        authorization = True
        following = Follow.objects.filter(
            user=request.user,
            author=author
        ).exists()
        if following:
            following = True
        else:
            following = False
    else:
        following = False
        authorization = False
    paginator = Paginator(posts, 10)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)
    context = {
        "author": author,
        "page_obj": page,
        "following": following,
        "authorization": authorization,
    }
    return render(request, "posts/profile.html", context)


@require_http_methods(["GET", "POST"])
def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    user = get_object_or_404(User, username=post.author)
    form = CommentForm(
        request.POST or None,
    )
    comments = Comment.objects.filter(post=post)
    return render(
        request,
        "posts/post.html",
        {
            "user": user,
            "post": post,
            "form": form,
            "comments": comments,
        },
    )


@require_http_methods(["POST", "GET"])
@login_required
def new_post(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        new = form.save(commit=False)
        new.author = request.user
        new.save()
        return redirect("posts:profile", username=request.user)
    return render(
        request,
        "posts/form.html",
        {
            "form": form,
        },
    )


@require_http_methods(["GET", "POST"])
@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id, author__username=request.user)
    form = PostForm(
        request.POST or None, files=request.FILES or None, instance=post
    )
    if post.author != request.user:
        return redirect("posts:post_detail", post_id=post_id)
    if form.is_valid():
        post.save()
        return redirect("posts:post_detail", post_id=post_id)
    return render(
        request,
        "posts/edit_post.html",
        {"form": form, "post": post, "is_edit": True},
    )


@require_http_methods(["POST"])
@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect("posts:post_detail", post_id=post_id)


@login_required
def follow_index(request):
    user = request.user
    posts = Post.objects.filter(author__following__user=user)
    paginator = Paginator(posts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {"page_obj": page_obj, "posts": posts}
    return render(request, "posts/follow.html", context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect("posts:profile", author)


@login_required
def profile_unfollow(request, username):
    follower = get_object_or_404(
        Follow, user=request.user, author__username=username
    )
    follower.delete()
    return redirect("posts:profile", username)

yatube/templates/posts/edit_post.html
{% extends "base.html" %}
{% block title %}Редактировать запись{% endblock %}
{% block content %}
  {% load user_filters %}

  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Редактировать запись</div>
        <div class="card-body">

          {% for error in form.errors %}
            <div class="alert alert-danger" role="alert">
              {{ error }}
            </div>
          {% endfor %}

          <form method="post" action="{% url 'posts:post_edit' post.pk %}" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row" aria-required={{ field.field.required }}>
                <label
                  for="{{ field.id_for_label }}"
                  class="col-md-4 col-form-label text-md-right">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required">*</span>
                  {% endif %}
                </label>
                <div class="col-md-6">
                  {# подключаем фильтр и указываем класс #}
                  {{ field|addclass:"form-control" }}
                  {% if field.help_text %}
                    <small
                      id="{{ field.id_for_label }}-help"
                      class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Cохранить
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->

{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    <h3>
      <div class="card mb-3 mt-1 shadow-sm">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img" src="{{ im.url }}">
        {% endthumbnail %}
        <div class="card-body">
      Автор: <a href="{% url 'posts:profile' post.author.username %}">
      <strong class="d-block text-gray-dark">{{post.author.get_full_name}}.</strong>
      </a>
      <p>
      Дата публикации: {{post.pub_date|date:"d M Y"}}<br>
      </p>
      {% if post.group %}
        <a href="{% url 'posts:group_posts' post.group.slug %}"  
        type="button" class="btn btn-outline-primary"># {{post.group}}</a>
      {% endif %}
    </h3>
    <p>{{post.text|linebreaksbr}}</p><br>
    <a href="{% url 'posts:post_detail' post.id %}" type="button" class="btn btn-outline-primary">
      Перейти к посту
    </a>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'paginator.html' %}
{% endblock %}

yatube/templates/posts/form.html
{% extends "base.html" %}
{% block title %}Новая запись{% endblock %}
{% block content %}
  {% load user_filters %}

  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Создать новую запись</div>
        <div class="card-body">

          {% for error in form.errors %}
            <div class="alert alert-danger" role="alert">
              {{ error }}
            </div>
          {% endfor %}

          <form method="post" action="{% url 'posts:new_post' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row" aria-required={{ field.field.required }}>
                <label
                  for="{{ field.id_for_label }}"
                  class="col-md-4 col-form-label text-md-right">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required">*</span>
                  {% endif %}
                </label>
                <div class="col-md-6">
                  {# подключаем фильтр и указываем класс #}
                  {{ field|addclass:"form-control" }}
                  {% if field.help_text %}
                    <small
                      id="{{ field.id_for_label }}-help"
                      class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Создать запись
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->

{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block header %}{{ group.title }}{% endblock %}
{% block content %}
  <p>{{ group.description }}</p>
  <br>
  {% for post in page_obj %}
    <h3>
      <div class="card mb-3 mt-1 shadow-sm">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img" src="{{ im.url }}">
        {% endthumbnail %}
        <div class="card-body">
        Автор: {{ post.author.get_full_name }},
        Дата публикации: {{ post.pub_date|date:"d M Y" }}
    </h3>
    <p>{{post.text|linebreaksbr}}</p><br>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% include "paginator.html" %}
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load cache %}
{% load thumbnail %}
{% cache 500 index_page %}
{% block header %}Последнии обновления на сайте{% endblock %}
{% block title %}Последнии обновления на сайте{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  <br>
  {% for post in page_obj %}
    <h3>
      <div class="card mb-3 mt-1 shadow-sm">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img" src="{{ im.url }}">
        {% endthumbnail %}
        <div class="card-body">
      Автор: <a href="{% url 'posts:profile' post.author.username %}">
      <strong class="d-block text-gray-dark">{{post.author.get_full_name}}.</strong>
      </a>
      <p>
      Дата публикации: {{post.pub_date|date:"d M Y"}}<br>
      </p>
      {% if post.group %}
        <a href="{% url 'posts:group_posts' post.group.slug %}"  
        type="button" class="btn btn-outline-primary"># {{post.group}}</a>
      {% endif %}
    </h3>
    <p>{{post.text|linebreaksbr}}</p><br>
    <a href="{% url 'posts:post_detail' post.id %}" type="button" class="btn btn-outline-primary">
      Перейти к посту
    </a>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% include "paginator.html" %}
{% endblock %}
{% endcache %}

yatube/templates/posts/post.html
{% extends "base.html" %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}{{ post }}{% endblock %}
{% block content %}
    <main>
      {% csrf_token %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"j E Y" }}
            </li>
            {% if post.group %}  
              <li class="list-group-item">
                Группа: {{ post.group }}
                <a href="{% url 'posts:group_posts' post.group.slug %}">
                  все записи группы
                </a>
              </li>
              {% endif %}
              <li class="list-group-item">
                Автор: {{ user.get_full_name }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ user.posts.count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' user %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
           {{ post.text }}
          </p>
          {% if request.user == user %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
            редактировать запись
          </a>
          {% endif %}
          {% if user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" action="{% url 'posts:add_comment' post.id %}">
                {% csrf_token %}      
                <div class="form-group mb-2">
                  {{ form.text|addclass:"form-control" }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
              </form>
            </div>
          </div>
        {% endif %}

        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                </a>
              </h5>
                <p>
                {{ comment.text }}
                </p>
              </div>
            </div>
        {% endfor %} 
        </article>
      </div> 
    </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Профайл пользователя {{ author.get_full_name }}{% endblock %}
{% block content %}
    <main>
      <div class="container py-5">        
        <h1>Все посты пользователя {{ author }} </h1>
        <h3>Всего постов: {{ author.posts.count }} </h3>
        {% if authorization %}
        {% if request.user != author %}
        {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
       {% endif %}
       {% endif %}
       {% endif %}
        <article>
          {% for post in page_obj %}
          <ul>
            <li>
              Дата публикации: {{ post.pub_date|date:"j E Y" }} 
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
          {{ post.text }} 
          </p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a><br>
        </article>
        {% if post.group %}
        <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        <!-- Остальные посты. после последнего нет черты -->
        <!-- Здесь подключён паджинатор -->  
        {% include "paginator.html" %}
      </div>
    </main>
{% endblock %}